name: Run tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev, fix ]

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                php: [8.0, 7.4, 7.3]
                laravel: [8.*, 7.*]
                os: [ubuntu-latest]
                include:
                    - laravel: 8.*
                      testbench: 6.*
                    - laravel: 7.*
                      testbench: 5.*
                exclude:
                    - laravel: 7.*
                      php: 8.0

        name: PHP ${{ matrix.php }} with Laravel ${{ matrix.laravel }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, pdo, sqlite, pdo_sqlite
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --prefer-dist --no-interaction --no-suggest

            - name: Execute pest tests
              run: vendor/bin/pest